name: Run Azure Login with OIDC
# https://docs.github.com/en/actions/how-tos/secure-your-work/security-harden-deployments/oidc-in-azure
on: [workflow_dispatch]

permissions:
  id-token: write
  contents: read
jobs:
  download:
    environment: AIForGood
    runs-on: ubuntu-latest
    steps:
      - name: AZ CLI login
        uses: azure/login@v2.3.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Check Environment Variables
        env:
            TEST_ENV_VAR: ${{ vars.TEST_ENV_VAR }}
        run: |
            echo $TEST_ENV_VAR

      - name: Azure CLI script
        continue-on-error: true
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az storage container list --account-name dshydro --query "[].name"

      - name: Test download from Azure Blob Storage
        run: |
            az storage blob download \
                --account-name dshydro\
                --container-name accelerator2025 \
                --name README.md \
                --file /tmp/README.md
